name: Build images
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - .gitignore
      - 'docs/**'
      - 'theme/**'
      - book.toml
      - .github/workflows/docs.yaml

jobs:
  query:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Query available board configs
        id: query
        run: |
          echo "boards=$(./rbuild json boards)"
          echo "suites=$(./rbuild json suites)"
          echo "flavors=$(./rbuild json flavors)"
 
  download-latest-rt-kernel:
      runs-on: ubuntu-latest
      steps:
        - name: download-artifact
          uses: bettermarks/action-artifact-download@0.3.0
          with:
            repo: pissalou/bsp
            token: ${{ secrets.GITHUB_TOKEN }}
            artifact_name: linux_rockchip_1
            rename: linux_rockchip_kernel_packages    
            wait_seconds: 60  
    
  build-rootfs:
    needs: query
    runs-on: ubuntu-latest
    strategy:
      matrix:
        boards: [ rootfs ]
        suites: [ bullseye ]
        flavors: [ cli ]
    steps:
      - name: Build ${{ matrix.boards }}_${{ matrix.suites }}_${{ matrix.flavors }}
        uses: radxa-repo/rbuild@main
        with:
          board: ${{ matrix.boards }}
          suite: ${{ matrix.suites }}
          flavor: ${{ matrix.flavors }}
          test-repo: true
          artifacts: true

  build-images:
    needs: [ query, build-rootfs ]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        boards: [ rock-4se ]
        suites: [ bullseye ]
        flavors: [ cli ]
        exclude:
          - boards: rootfs
    steps:
      - name: Build ${{ matrix.boards }}_${{ matrix.suites }}_${{ matrix.flavors }}
        uses: radxa-repo/rbuild@main
        with:
          board: ${{ matrix.boards }}
          suite: ${{ matrix.suites }}
          flavor: ${{ matrix.flavors }}
          test-repo: true
          artifacts: true
          prebuilt-rootfs: true
